### PR TITLE
should solve issue #2, vimeo support

### PR DESCRIPTION
**Pull request by Andi-Lo**
- Added some dummy content for testing the vimeo feature
- Added the PageItemVimeo
- Testet the feature with captions (they have to be named after the vimeo file e.g. 1.vimeo and 1.txt) and adding the vimeo video to different content sections.

### CODE REVIEW

**Comment by Andi-Lo** [comment]
I tried to merge with the master branch but it has some merging conflicts with the bundle.js file (that could be expected). So I just tried to rebuild the bundle.js file (via gulp build) but it seems there is something missing in the repository. I get the error: 
`Error: Cannot find module 'markdown' from 'C:\Users\Andi\Documents\workspace\dmd-documentation-generator\src\utils'`

Seems like Markdown is missing in the src/utils folder.

**Comment by b-g** [comment]
The markdown dependency was correctly added to package.json ... Did you run 'npm install'?

**Comment by Andi-Lo** [comment]
ah I see :+1: , did not see the dependency change. Should have it fixed now with commit #fe654de

**Comment by b-g** [comment]
Thanks for this! Please add/fix:
- Video has an odd border style ... please remove any borders, should sit seamless in the layout
- We agreed to have a `1.vimeo` config file with the following content. Currently the file just has the id, but it is important to have full control of the video dimensions ...

``` json
{
"id": 157991947,
"width": 1920,
"height": 1080
}
```

**Comment by Andi-Lo** [comment]
How would I parse this json data from the file in react?
At the moment I got in Collection.react.js this:

``` javascript
case 'VIMEO':
    return (<PageItemVimeo key={_.uniqueId()} vimeoId={item.content}/>);
    break;
```

but now I would need width and height as properties too.

**Comment by b-g** [comment]
I guess simply by `JSON.parse(item.content)` ...

**Comment by Andi-Lo** [comment]
Okay the structure is now as intended and I removed the iframe border via CSS.

**Comment by b-g** [comment]
👍 + thanks!

**Pull request merged**
